name: Node.js CI/CD

on:
  push:
    branches: [ dev, uat, prod ]
  pull_request:
    branches: [ dev, uat, prod ]
  workflow_dispatch:

jobs:
  # ✅ Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npx eslint .

      - name: Run tests
        run: npm test

  # ✅ Test Job (Optional Separate Stage)
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npm test

  # ✅ Deploy to DEV (only from dev branch)
  deploy_dev:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Deploy to DEV
        run: echo "Deploying to DEV..."

  # ✅ Deploy to UAT (only from uat branch)
  deploy_uat:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/uat'
    steps:
      - name: Deploy to UAT
        run: echo "Deploying to UAT..."

  # ✅ Deploy to PROD (only from prod branch with manual gate)
  deploy_prod:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/prod' && github.event_name == 'workflow_dispatch'
    environment:
      name: production
      url: https://your-prod-url.com
    steps:
      - name: Deploy to PROD
        run: echo "Deploying to PROD..."
