name: Node.js CI

on:
  push:
    branches: [ dev, uat, prod ]
  pull_request:
    branches: [ dev, uat, prod ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Lint code
      run: npx eslint .

    - name: Run tests
      run: npm test
